version: '3.8'

services:
  # Next.js ERP UI Application
  erp-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-ui
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Add your API URL and other environment variables here
      # - NEXT_PUBLIC_API_URL=http://api:8000
    restart: unless-stopped
    networks:
      - erp-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  erp-network:
    driver: bridge
